frr defaults traditional
hostname frr-rr-b
!
router bgp 4200000000
 bgp router-id 10.201.255.2
 bgp cluster-id 10.201.99.99
 no bgp ebgp-requires-policy
 neighbor RR-CLIENTS peer-group
 neighbor RR-CLIENTS remote-as 4200000000
 neighbor RR-CLIENTS route-reflector-client
 neighbor RR-CLIENTS soft-reconfiguration inbound
 neighbor 10.201.0.6 peer-group RR-CLIENTS
 neighbor 10.201.0.6 description hub
 neighbor 10.201.0.14 peer-group RR-CLIENTS
 neighbor 10.201.0.14 description spoke-a
 neighbor 10.201.0.22 peer-group RR-CLIENTS
 neighbor 10.201.0.22 description spoke-b
 neighbor 10.201.1.1 remote-as 4200000000
 neighbor 10.201.1.1 description rr-peer frr-rr-a
 !
 address-family ipv4 unicast
  neighbor RR-CLIENTS activate
  neighbor 10.201.1.1 activate
  redistribute connected
 exit-address-family
!
line vty
!
