//go:build !ignore_autogenerated

/*
Copyright 2026 phenixblue.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActiveHealthConfig) DeepCopyInto(out *ActiveHealthConfig) {
	*out = *in
	if in.Interval != nil {
		in, out := &in.Interval, &out.Interval
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.UnhealthyThreshold != nil {
		in, out := &in.UnhealthyThreshold, &out.UnhealthyThreshold
		*out = new(int32)
		**out = **in
	}
	if in.HealthyThreshold != nil {
		in, out := &in.HealthyThreshold, &out.HealthyThreshold
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActiveHealthConfig.
func (in *ActiveHealthConfig) DeepCopy() *ActiveHealthConfig {
	if in == nil {
		return nil
	}
	out := new(ActiveHealthConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdvertisedBackend) DeepCopyInto(out *AdvertisedBackend) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdvertisedBackend.
func (in *AdvertisedBackend) DeepCopy() *AdvertisedBackend {
	if in == nil {
		return nil
	}
	out := new(AdvertisedBackend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AdvertisedBackend) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdvertisedBackendList) DeepCopyInto(out *AdvertisedBackendList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AdvertisedBackend, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdvertisedBackendList.
func (in *AdvertisedBackendList) DeepCopy() *AdvertisedBackendList {
	if in == nil {
		return nil
	}
	out := new(AdvertisedBackendList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AdvertisedBackendList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdvertisedBackendSpec) DeepCopyInto(out *AdvertisedBackendSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdvertisedBackendSpec.
func (in *AdvertisedBackendSpec) DeepCopy() *AdvertisedBackendSpec {
	if in == nil {
		return nil
	}
	out := new(AdvertisedBackendSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdvertisedBackendStatus) DeepCopyInto(out *AdvertisedBackendStatus) {
	*out = *in
	out.Locality = in.Locality
	in.Attributes.DeepCopyInto(&out.Attributes)
	if in.FirstSeen != nil {
		in, out := &in.FirstSeen, &out.FirstSeen
		*out = (*in).DeepCopy()
	}
	if in.LastChange != nil {
		in, out := &in.LastChange, &out.LastChange
		*out = (*in).DeepCopy()
	}
	in.Stability.DeepCopyInto(&out.Stability)
	if in.BoundPolicies != nil {
		in, out := &in.BoundPolicies, &out.BoundPolicies
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.GeneratedResources != nil {
		in, out := &in.GeneratedResources, &out.GeneratedResources
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdvertisedBackendStatus.
func (in *AdvertisedBackendStatus) DeepCopy() *AdvertisedBackendStatus {
	if in == nil {
		return nil
	}
	out := new(AdvertisedBackendStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BGPBackendPolicy) DeepCopyInto(out *BGPBackendPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BGPBackendPolicy.
func (in *BGPBackendPolicy) DeepCopy() *BGPBackendPolicy {
	if in == nil {
		return nil
	}
	out := new(BGPBackendPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BGPBackendPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BGPBackendPolicyList) DeepCopyInto(out *BGPBackendPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BGPBackendPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BGPBackendPolicyList.
func (in *BGPBackendPolicyList) DeepCopy() *BGPBackendPolicyList {
	if in == nil {
		return nil
	}
	out := new(BGPBackendPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BGPBackendPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BGPBackendPolicySpec) DeepCopyInto(out *BGPBackendPolicySpec) {
	*out = *in
	out.TargetRef = in.TargetRef
	in.Selector.DeepCopyInto(&out.Selector)
	in.Backend.DeepCopyInto(&out.Backend)
	in.LoadBalancing.DeepCopyInto(&out.LoadBalancing)
	if in.ActiveHealth != nil {
		in, out := &in.ActiveHealth, &out.ActiveHealth
		*out = new(ActiveHealthConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.OutlierDetection != nil {
		in, out := &in.OutlierDetection, &out.OutlierDetection
		*out = new(OutlierDetectionConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BGPBackendPolicySpec.
func (in *BGPBackendPolicySpec) DeepCopy() *BGPBackendPolicySpec {
	if in == nil {
		return nil
	}
	out := new(BGPBackendPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BGPBackendPolicyStatus) DeepCopyInto(out *BGPBackendPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Generated != nil {
		in, out := &in.Generated, &out.Generated
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BGPBackendPolicyStatus.
func (in *BGPBackendPolicyStatus) DeepCopy() *BGPBackendPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(BGPBackendPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BGPGatewayClassConfig) DeepCopyInto(out *BGPGatewayClassConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BGPGatewayClassConfig.
func (in *BGPGatewayClassConfig) DeepCopy() *BGPGatewayClassConfig {
	if in == nil {
		return nil
	}
	out := new(BGPGatewayClassConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BGPGatewayClassConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BGPGatewayClassConfigList) DeepCopyInto(out *BGPGatewayClassConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BGPGatewayClassConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BGPGatewayClassConfigList.
func (in *BGPGatewayClassConfigList) DeepCopy() *BGPGatewayClassConfigList {
	if in == nil {
		return nil
	}
	out := new(BGPGatewayClassConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BGPGatewayClassConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BGPGatewayClassConfigSpec) DeepCopyInto(out *BGPGatewayClassConfigSpec) {
	*out = *in
	if in.Foo != nil {
		in, out := &in.Foo, &out.Foo
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BGPGatewayClassConfigSpec.
func (in *BGPGatewayClassConfigSpec) DeepCopy() *BGPGatewayClassConfigSpec {
	if in == nil {
		return nil
	}
	out := new(BGPGatewayClassConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BGPGatewayClassConfigStatus) DeepCopyInto(out *BGPGatewayClassConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BGPGatewayClassConfigStatus.
func (in *BGPGatewayClassConfigStatus) DeepCopy() *BGPGatewayClassConfigStatus {
	if in == nil {
		return nil
	}
	out := new(BGPGatewayClassConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BGPPeer) DeepCopyInto(out *BGPPeer) {
	*out = *in
	if in.Auth != nil {
		in, out := &in.Auth, &out.Auth
		*out = new(BGPPeerAuth)
		(*in).DeepCopyInto(*out)
	}
	if in.GracefulRestart != nil {
		in, out := &in.GracefulRestart, &out.GracefulRestart
		*out = new(GracefulRestartConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Timers != nil {
		in, out := &in.Timers, &out.Timers
		*out = new(BGPTimers)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BGPPeer.
func (in *BGPPeer) DeepCopy() *BGPPeer {
	if in == nil {
		return nil
	}
	out := new(BGPPeer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BGPPeerAuth) DeepCopyInto(out *BGPPeerAuth) {
	*out = *in
	if in.TCPMD5SecretRef != nil {
		in, out := &in.TCPMD5SecretRef, &out.TCPMD5SecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BGPPeerAuth.
func (in *BGPPeerAuth) DeepCopy() *BGPPeerAuth {
	if in == nil {
		return nil
	}
	out := new(BGPPeerAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BGPPeerConfig) DeepCopyInto(out *BGPPeerConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BGPPeerConfig.
func (in *BGPPeerConfig) DeepCopy() *BGPPeerConfig {
	if in == nil {
		return nil
	}
	out := new(BGPPeerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BGPPeerConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BGPPeerConfigList) DeepCopyInto(out *BGPPeerConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BGPPeerConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BGPPeerConfigList.
func (in *BGPPeerConfigList) DeepCopy() *BGPPeerConfigList {
	if in == nil {
		return nil
	}
	out := new(BGPPeerConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BGPPeerConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BGPPeerConfigSpec) DeepCopyInto(out *BGPPeerConfigSpec) {
	*out = *in
	if in.ListenPort != nil {
		in, out := &in.ListenPort, &out.ListenPort
		*out = new(int32)
		**out = **in
	}
	if in.Peers != nil {
		in, out := &in.Peers, &out.Peers
		*out = make([]BGPPeer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ClusterBindings != nil {
		in, out := &in.ClusterBindings, &out.ClusterBindings
		*out = make([]ClusterBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BGPPeerConfigSpec.
func (in *BGPPeerConfigSpec) DeepCopy() *BGPPeerConfigSpec {
	if in == nil {
		return nil
	}
	out := new(BGPPeerConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BGPPeerConfigStatus) DeepCopyInto(out *BGPPeerConfigStatus) {
	*out = *in
	if in.Peers != nil {
		in, out := &in.Peers, &out.Peers
		*out = make([]PeerStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BGPPeerConfigStatus.
func (in *BGPPeerConfigStatus) DeepCopy() *BGPPeerConfigStatus {
	if in == nil {
		return nil
	}
	out := new(BGPPeerConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BGPStabilityConfig) DeepCopyInto(out *BGPStabilityConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BGPStabilityConfig.
func (in *BGPStabilityConfig) DeepCopy() *BGPStabilityConfig {
	if in == nil {
		return nil
	}
	out := new(BGPStabilityConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BGPStabilityConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BGPStabilityConfigList) DeepCopyInto(out *BGPStabilityConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BGPStabilityConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BGPStabilityConfigList.
func (in *BGPStabilityConfigList) DeepCopy() *BGPStabilityConfigList {
	if in == nil {
		return nil
	}
	out := new(BGPStabilityConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BGPStabilityConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BGPStabilityConfigSpec) DeepCopyInto(out *BGPStabilityConfigSpec) {
	*out = *in
	if in.WithdrawalGrace != nil {
		in, out := &in.WithdrawalGrace, &out.WithdrawalGrace
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.AdditionDelay != nil {
		in, out := &in.AdditionDelay, &out.AdditionDelay
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.Dampening != nil {
		in, out := &in.Dampening, &out.Dampening
		*out = new(DampeningConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BGPStabilityConfigSpec.
func (in *BGPStabilityConfigSpec) DeepCopy() *BGPStabilityConfigSpec {
	if in == nil {
		return nil
	}
	out := new(BGPStabilityConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BGPStabilityConfigStatus) DeepCopyInto(out *BGPStabilityConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BGPStabilityConfigStatus.
func (in *BGPStabilityConfigStatus) DeepCopy() *BGPStabilityConfigStatus {
	if in == nil {
		return nil
	}
	out := new(BGPStabilityConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BGPTimers) DeepCopyInto(out *BGPTimers) {
	*out = *in
	if in.Hold != nil {
		in, out := &in.Hold, &out.Hold
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.Keepalive != nil {
		in, out := &in.Keepalive, &out.Keepalive
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BGPTimers.
func (in *BGPTimers) DeepCopy() *BGPTimers {
	if in == nil {
		return nil
	}
	out := new(BGPTimers)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackendAttributes) DeepCopyInto(out *BackendAttributes) {
	*out = *in
	if in.ServiceTag != nil {
		in, out := &in.ServiceTag, &out.ServiceTag
		*out = new(int32)
		**out = **in
	}
	if in.ASPath != nil {
		in, out := &in.ASPath, &out.ASPath
		*out = make([]int64, len(*in))
		copy(*out, *in)
	}
	if in.LargeCommunities != nil {
		in, out := &in.LargeCommunities, &out.LargeCommunities
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackendAttributes.
func (in *BackendAttributes) DeepCopy() *BackendAttributes {
	if in == nil {
		return nil
	}
	out := new(BackendAttributes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackendConfig) DeepCopyInto(out *BackendConfig) {
	*out = *in
	if in.AppProtocol != nil {
		in, out := &in.AppProtocol, &out.AppProtocol
		*out = new(string)
		**out = **in
	}
	in.TLS.DeepCopyInto(&out.TLS)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackendConfig.
func (in *BackendConfig) DeepCopy() *BackendConfig {
	if in == nil {
		return nil
	}
	out := new(BackendConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackendSelector) DeepCopyInto(out *BackendSelector) {
	*out = *in
	if in.Prefixes != nil {
		in, out := &in.Prefixes, &out.Prefixes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ServiceTag != nil {
		in, out := &in.ServiceTag, &out.ServiceTag
		*out = new(int32)
		**out = **in
	}
	if in.ClusterIDs != nil {
		in, out := &in.ClusterIDs, &out.ClusterIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackendSelector.
func (in *BackendSelector) DeepCopy() *BackendSelector {
	if in == nil {
		return nil
	}
	out := new(BackendSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackendTLSConfig) DeepCopyInto(out *BackendTLSConfig) {
	*out = *in
	if in.CredentialRef != nil {
		in, out := &in.CredentialRef, &out.CredentialRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackendTLSConfig.
func (in *BackendTLSConfig) DeepCopy() *BackendTLSConfig {
	if in == nil {
		return nil
	}
	out := new(BackendTLSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterBinding) DeepCopyInto(out *ClusterBinding) {
	*out = *in
	if in.AllowedPrefixes != nil {
		in, out := &in.AllowedPrefixes, &out.AllowedPrefixes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MaxPrefixes != nil {
		in, out := &in.MaxPrefixes, &out.MaxPrefixes
		*out = new(int32)
		**out = **in
	}
	out.Locality = in.Locality
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterBinding.
func (in *ClusterBinding) DeepCopy() *ClusterBinding {
	if in == nil {
		return nil
	}
	out := new(ClusterBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommunityFallbacks) DeepCopyInto(out *CommunityFallbacks) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommunityFallbacks.
func (in *CommunityFallbacks) DeepCopy() *CommunityFallbacks {
	if in == nil {
		return nil
	}
	out := new(CommunityFallbacks)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommunityFieldSet) DeepCopyInto(out *CommunityFieldSet) {
	*out = *in
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommunityFieldSet.
func (in *CommunityFieldSet) DeepCopy() *CommunityFieldSet {
	if in == nil {
		return nil
	}
	out := new(CommunityFieldSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommunityMap) DeepCopyInto(out *CommunityMap) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommunityMap.
func (in *CommunityMap) DeepCopy() *CommunityMap {
	if in == nil {
		return nil
	}
	out := new(CommunityMap)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CommunityMap) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommunityMapList) DeepCopyInto(out *CommunityMapList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CommunityMap, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommunityMapList.
func (in *CommunityMapList) DeepCopy() *CommunityMapList {
	if in == nil {
		return nil
	}
	out := new(CommunityMapList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CommunityMapList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommunityMapSpec) DeepCopyInto(out *CommunityMapSpec) {
	*out = *in
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]CommunityRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Fallbacks != nil {
		in, out := &in.Fallbacks, &out.Fallbacks
		*out = new(CommunityFallbacks)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommunityMapSpec.
func (in *CommunityMapSpec) DeepCopy() *CommunityMapSpec {
	if in == nil {
		return nil
	}
	out := new(CommunityMapSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommunityMapStatus) DeepCopyInto(out *CommunityMapStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommunityMapStatus.
func (in *CommunityMapStatus) DeepCopy() *CommunityMapStatus {
	if in == nil {
		return nil
	}
	out := new(CommunityMapStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommunityMatch) DeepCopyInto(out *CommunityMatch) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommunityMatch.
func (in *CommunityMatch) DeepCopy() *CommunityMatch {
	if in == nil {
		return nil
	}
	out := new(CommunityMatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommunityRule) DeepCopyInto(out *CommunityRule) {
	*out = *in
	out.Match = in.Match
	in.Set.DeepCopyInto(&out.Set)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommunityRule.
func (in *CommunityRule) DeepCopy() *CommunityRule {
	if in == nil {
		return nil
	}
	out := new(CommunityRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DampeningConfig) DeepCopyInto(out *DampeningConfig) {
	*out = *in
	if in.HalfLife != nil {
		in, out := &in.HalfLife, &out.HalfLife
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.SuppressThreshold != nil {
		in, out := &in.SuppressThreshold, &out.SuppressThreshold
		*out = new(int32)
		**out = **in
	}
	if in.ReuseThreshold != nil {
		in, out := &in.ReuseThreshold, &out.ReuseThreshold
		*out = new(int32)
		**out = **in
	}
	if in.MaxSuppress != nil {
		in, out := &in.MaxSuppress, &out.MaxSuppress
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DampeningConfig.
func (in *DampeningConfig) DeepCopy() *DampeningConfig {
	if in == nil {
		return nil
	}
	out := new(DampeningConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GracefulRestartConfig) DeepCopyInto(out *GracefulRestartConfig) {
	*out = *in
	if in.StaleRoutesTime != nil {
		in, out := &in.StaleRoutesTime, &out.StaleRoutesTime
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GracefulRestartConfig.
func (in *GracefulRestartConfig) DeepCopy() *GracefulRestartConfig {
	if in == nil {
		return nil
	}
	out := new(GracefulRestartConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancingConfig) DeepCopyInto(out *LoadBalancingConfig) {
	*out = *in
	if in.Locality != nil {
		in, out := &in.Locality, &out.Locality
		*out = new(LocalityLoadBalancingConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancingConfig.
func (in *LoadBalancingConfig) DeepCopy() *LoadBalancingConfig {
	if in == nil {
		return nil
	}
	out := new(LoadBalancingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Locality) DeepCopyInto(out *Locality) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Locality.
func (in *Locality) DeepCopy() *Locality {
	if in == nil {
		return nil
	}
	out := new(Locality)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalityLoadBalancingConfig) DeepCopyInto(out *LocalityLoadBalancingConfig) {
	*out = *in
	if in.Preference != nil {
		in, out := &in.Preference, &out.Preference
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.FailoverThreshold != nil {
		in, out := &in.FailoverThreshold, &out.FailoverThreshold
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalityLoadBalancingConfig.
func (in *LocalityLoadBalancingConfig) DeepCopy() *LocalityLoadBalancingConfig {
	if in == nil {
		return nil
	}
	out := new(LocalityLoadBalancingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OutlierDetectionConfig) DeepCopyInto(out *OutlierDetectionConfig) {
	*out = *in
	if in.Consecutive5xx != nil {
		in, out := &in.Consecutive5xx, &out.Consecutive5xx
		*out = new(int32)
		**out = **in
	}
	if in.BaseEjectionTime != nil {
		in, out := &in.BaseEjectionTime, &out.BaseEjectionTime
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.MaxEjectionPercent != nil {
		in, out := &in.MaxEjectionPercent, &out.MaxEjectionPercent
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OutlierDetectionConfig.
func (in *OutlierDetectionConfig) DeepCopy() *OutlierDetectionConfig {
	if in == nil {
		return nil
	}
	out := new(OutlierDetectionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PeerStatus) DeepCopyInto(out *PeerStatus) {
	*out = *in
	if in.Uptime != nil {
		in, out := &in.Uptime, &out.Uptime
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PeerStatus.
func (in *PeerStatus) DeepCopy() *PeerStatus {
	if in == nil {
		return nil
	}
	out := new(PeerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StabilityStatus) DeepCopyInto(out *StabilityStatus) {
	*out = *in
	if in.LastObservedAt != nil {
		in, out := &in.LastObservedAt, &out.LastObservedAt
		*out = (*in).DeepCopy()
	}
	if in.WithdrawnAt != nil {
		in, out := &in.WithdrawnAt, &out.WithdrawnAt
		*out = (*in).DeepCopy()
	}
	if in.SuppressedSince != nil {
		in, out := &in.SuppressedSince, &out.SuppressedSince
		*out = (*in).DeepCopy()
	}
	if in.PendingSince != nil {
		in, out := &in.PendingSince, &out.PendingSince
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StabilityStatus.
func (in *StabilityStatus) DeepCopy() *StabilityStatus {
	if in == nil {
		return nil
	}
	out := new(StabilityStatus)
	in.DeepCopyInto(out)
	return out
}
