frr defaults traditional
hostname frr-rr-a
!
ip prefix-list UNDERLAY-ONLY seq 5 permit 10.201.0.0/24 le 30
ip prefix-list UNDERLAY-ONLY seq 10 permit 10.201.1.0/30
!
route-map RR-PEER-IN permit 10
 match ip address prefix-list UNDERLAY-ONLY
!
router bgp 4200000000
 bgp router-id 10.201.255.1
 bgp cluster-id 10.201.99.99
 no bgp ebgp-requires-policy
 neighbor RR-CLIENTS peer-group
 neighbor RR-CLIENTS remote-as 4200000000
 neighbor RR-CLIENTS route-reflector-client
 neighbor RR-CLIENTS soft-reconfiguration inbound
 neighbor 10.201.0.2 peer-group RR-CLIENTS
 neighbor 10.201.0.2 description hub
 neighbor 10.201.0.10 peer-group RR-CLIENTS
 neighbor 10.201.0.10 description spoke-a
 neighbor 10.201.0.18 peer-group RR-CLIENTS
 neighbor 10.201.0.18 description spoke-b
 neighbor 10.201.1.2 remote-as 4200000000
 neighbor 10.201.1.2 description rr-peer frr-rr-b
 !
 address-family ipv4 unicast
  neighbor RR-CLIENTS activate
  neighbor 10.201.1.2 activate
  neighbor 10.201.1.2 route-map RR-PEER-IN in
  redistribute connected
 exit-address-family
!
line vty
!
